name: merge yml

on:
    workflow_dispatch:
        inputs:
            branch_name:
              description: 'Branch Name'
              required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: step1
          run: |
            git checkout main
            git merge --squash nk/trial1
            git commit -m "Squashed trial"
            echo "Nur"


