name: merge yml

on:
    workflow_dispatch:
        inputs:
            branch_name:
              description: 'Branch Name'
              required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: step1
          run: |
            echo "Nur"