name: NUR2

env:
  manualEnvKey: ${{ github.event.inputs.envKey }}
  envKey: 'dev'

on:
  workflow_dispatch:
    inputs:
          envKey:
            description: 'Environment flag'
            required: true
            default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'NUR Step1'
        env:
          nur: 'nur_${{ github.event.inputs.envKey }}'
        run: |
          echo "envKey is $envKey"
          echo $nur



