name: NUR2

env:
  # WORKFLOW_NAME: MattrVIIPlatform
  manualEnvKey: ${{ github.event.inputs.envKey }}
  envKey: 'dev'
  # runName: '${{ github.event_name }} on ${{ github.event.inputs.envKey }} NUR'

# run-name: '${{ github.event_name }} ${{ github.ref_name }} ${{ github.event.head_commit.message }} ${{ github.event.inputs.envKey }}'

# run-name: '${{ github.ref_name }} ${{ env.WORKFLOW_NAME }}'

# run-name: '${{ github.ref_name }} ${{ github.workflow }}'

run-name: '${{ github.event_name }} ${{ github.event.head_commit.message }} ${{ github.workflow }} ${{ github.ref_name }} ${{ github.event.inputs.envKey }}'

on:
  workflow_dispatch:
    inputs:
          envKey:
            description: 'Environment flag'
            required: true
            default: 'dev'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'NUR Step1'
        env:
          nur: 'nur_${{ github.event.inputs.envKey }}'
        run: |
          echo "envKey is $envKey"
          echo 'nur_${{ github.event.inputs.envKey }}'



