name: NUR2

env:
  manualEnvKey: ${{ github.event.inputs.envKey }}
  envKey: 'dev'
  runName: '${{ github.event_name }} on ${{ github.event.inputs.envKey }} NUR'

run-name: ${{ env.runName }}

on:
  workflow_dispatch:
    inputs:
          envKey:
            description: 'Environment flag'
            required: true
            default: 'dev'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'NUR Step1'
        env:
          nur: 'nur_${{ github.event.inputs.envKey }}'
        run: |
          echo "envKey is $envKey"
          echo 'nur_${{ github.event.inputs.envKey }}'



