name: Kakapo-PVT

env:
  # use this env var to identify which workflow is running
  # e.g it can be used by report portal config to customize the launcher name
  WORKFLOW_NAME: KakapoPVT

  #miscellaneous env vars 
  ANNOTATION: "n/a"
  YARN_SCRIPT: "${{ github.event.inputs.select_mobile }}.kakapo.sauce"
  NODE_OPTIONS: "--max-old-space-size=5120"
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_PAT: ${{secrets.GH_TOKEN}}
  NGROK_AUTH_TOKEN: ${{secrets.NGROK_AUTH_TOKEN}}

permissions:
  actions: read
  contents: read
  id-token: write
  checks: write
  statuses: write
  
on:
  workflow_dispatch:
    inputs:
      git_reference:
        required: true
        description: JJ Target Git Version  
        default: "master"  
      select_mobile:
        required: true
        type: choice
        description: Mobile Type
        options:
          - android
          - ios 
      device_model:
        required: false
        type: choice
        description: Device Model
        options:
          - (android) Google Pixel (4|6|7).*
          - (android) Google Pixel 4.*
          - (android) Google Pixel 6.*
          - (android) Google Pixel 7.*
          - (ios) iPhone (14|13|12).*
          - (ios) iPhone 14.*
          - (ios) iPhone 13.*
          - (ios) iPhone 12.*
      wallet_version:
        required: false
        type: choice
        description: Mattr Wallet App Version
        default: '2.6.1'
        options:
          - 2.6.1
          - 2.5.1
      annotation:
        description: "[OPTIONAL] Test report annotations"
        required: false
  repository_dispatch:
    types: ["KakapoPVT"]

  schedule:
    # PROD: Runs every MON and WED 8am UTC (8pm NZT Winter, 9pm NZT Summer)
    - cron: "00 8 * * 1,3"

# walang checkout
# walang yarn build

jobs:
  kakapo-pvt:
    runs-on: [self-hosted, macos, e2e]
    timeout-minutes: 10
    env:
      yarnScript: ''

    steps:
      - name: Initialize Test Report Annotations
        run: |
          echo "envKey is $envKey"
          echo 'nur_${{ github.event.inputs.envKey }}'
